program: scripts/train.py
method: random
metric:
  name: val_mse
  goal: minimize
parameters:
  batch_size:
    values: [8, 16, 32]
  hidden_size:
    values: [32, 64, 128]
  num_layers:
    values: [1, 2, 3]
  dropout_rate:
    values: [0.1, 0.2, 0.3]
  lr:
    min: 0.0001
    max: 0.005
  epochs:
    values: [10, 15, 20]
  alpha:
    min: 0.3
    max: 0.7
