program: scripts/train.py
method: random  # Options: grid, random, bayes
metric:
  name: val_mse
  goal: minimize
parameters:
  batch_size:
    values: [16, 32, 64]
  hidden_size:
    values: [64, 128, 256]
  num_layers:
    values: [1, 2, 3]
  dropout_rate:
    values: [0.0, 0.1, 0.2]
  lr:
    min: 0.00001
    max: 0.001
  epochs:
    values: [6, 10, 15]
  alpha:
    min: 0.3
    max: 0.7


# Limit the number of sweep runs
count: 25